apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc
  name: svc
  namespace: hello-ingress
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-app
  type: ClusterIP
