apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc2
  name: svc2
  namespace: hello-ingress
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-app2
  type: ClusterIP
